services:
  gambit-http:
    build: ./gambit-http
    environment:
      - DATABASE_URL=mysql://root:devpass@mysql-db:3306/gambit
      - REDIS_HOST=redis-db
      - REDIS_PORT=6379
    ports:
      - 3001:3001
      # debugger
      - 9229:9229
    command: npm run dev
    volumes:
      - ./gambit-http:/srv/app
      # don't sync node modules
      - /srv/app/node_modules

  gambit-io:
    build: ./gambit-io
    environment:
      - REDIS_HOST=redis-db
      - REDIS_PORT=6379
    ports:
      - 3002:3002
      # debugger
      - 9239:9239
    command: npm run dev
    volumes:
      - ./gambit-io:/srv/app
      # don't sync node modules
      - /srv/app/node_modules

  mysql-db:
    image: mysql:9.0
    restart: always
    # TODO: MOVE ME TO ENV
    # (this is just an example, not intended to be a production configuration)
    environment:
      MYSQL_ROOT_PASSWORD: devpass
      MYSQL_DATABASE: gambit
    volumes:
      - ./db/data:/var/lib/mysql
    # this is only for dev work (workbench etc), not needed for app
    ports:
      - 3306:3306

  redis-db:
    image: redis:7.2
    restart: always
    ports:
      # only needed for dev work
      - 6379:6379
