services:
  nuxt-app:
    build: ./nuxt-app
    ports:
      - "3000:3000"
      # For hmr and other vite stuff
      - "24678:24678"
    # TODO: remove for prod
    volumes:
      - ./nuxt-app:/srv/app

  # TODO: HMR?
  express-app:
    build: ./express-app
    ports:
      - "3001:3001"

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    # TODO: MOVE ME TO ENV
    environment:
      - MYSQL_ROOT_PASSWORD=devpass
    volumes:
      - ./db/data:/var/lib/mysql
    # TODO: we only need communication from other containers, not externally
    ports:
      - 3306:3306
