services:
  nuxt-app:
    build: ./nuxt-app
    ports:
      - "3000:3000"
      # For hmr and other vite stuff
      - "24678:24678"
    # TODO: remove for prod
    volumes:
      - ./nuxt-app:/srv/app

  # TODO: HMR?
  express-app:
    build: ./express-app
    ports:
      - "3001:3001"
