services:
  express-app:
    build: ./express-app
    ports:
      - "3001:3001"

  db:
    image: mysql
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    # TODO: MOVE ME TO ENV
    environment:
      - MYSQL_ROOT_PASSWORD=devpass
    volumes:
      - ./db/data:/var/lib/mysql
    # TODO: we only need communication from other containers, not externally
    ports:
      - 3306:3306
